### ISSUE TITLE
[OSSPlanet] AOSC Application for VPS Plan

### ISSUE THREAD

**Issue by Yexiaoxing** [OSSPlanet/OSSPlanet#11]
(Please don't delete existing form title and description, just append your info/data under each section.)

* Applicant:
(Org/Project name <http://url.of.the/project/>)
Anthon Open Source Community <https://aosc.io>

* Project Info:
(Brief intro)
(Project fullname and mission)
(The relationship to Open Source/Culture/Music (and contribution it's it's a existing project).)

AOSC, short for Anthon Open Source Community, is a F/OSS focused community first established by Mingcong (Jeff) Bai and his classmates in 2011, initially with an intention to create a more easy-to-use Linux distribution with better CJK language support, they started the AnthonOS (later known as AOSC OS) project - the first, and still the largest project of the community.
AOSC's one and only pursuit is for the advancement of open technologies that benefits technology users like us who work for the community, and you who enjoys results from our effort.

* Contact:
(Format: name <email>, <telegram>, <github>, <hangout>, <twitter>, etc)
(Better to have at least 1 Instant Messanger. Telegram prefered.)
(can be more than one person)

Xiaoxing YE <xiaoxing@aosc.io> / Telegram: t.me/xiaoxing

* Who I am:
(Brief intro about who you are)
(what role in what project/team, responsible for what).

I'm SysAdmin of AOSC.

* Verification:
(If it's a existing project, please provide a link to a page on project site (or othe possibly method) to verify your identity and proof that you or the contact person can represent the (sub-)project/team.)

https://aosc.io/people/~yexiaoxing

* Resource you need:
(Please describe and list down "How many, which kind (VM, web hosting, git hosting, mirror service, etc), usage (will it be what kind of function/role) and spec.")
(Please describe both the Minimal and Desired spec.)
(For slave mirror service, please also give us the source url, mirror frequecy, and other neccessary info.)

1 x VM for mail gateway (@aosc.<io,xyz> domail mail).
Minimal: 512MB，5GB HDD

* Any additional info.

* Ability to promote OSSPlanet
As this is a free service for Open Source/Culture/Music without asking almost nothing in return,
We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.
And if it's ok for you, please let us know!

We have put OSSPlanet in our sponsor list :)

**Comment by bluet** [comment]
Done. Forgot to close.
