### ISSUE TITLE
[OSSPlanet] AlmaLinux Application for Mirror Plan

### ISSUE THREAD

**Issue by jonathanspw** [OSSPlanet/OSSPlanet#24]
* Applicant:
(Org/Project name <http://url.of.the/project/>)
https://almalinux.org

* Project Info:
(Brief intro)
(Project fullname and mission)
(The relationship to Open Source/Culture/Music (and contribution it's it's a existing project).)
tl;dr is a CentOS replacement - 1:1 repack of RHEL.

* Contact:
(Format: name <email>, <telegram>, <github>, <hangout>, <twitter>, etc)
(Better to have at least 1 Instant Messanger. Telegram prefered, as we have official support group here https://telegram.me/ossplanet .)
(can be more than one person)
Jonathan Wright <jonathan[at]almalinux.org> https://twitter.com/jonathanspw

* Who I am:
(Brief intro about who you are)
(what role in what project/team, responsible for what).
Infrastructure Team Lead.  I do all things infra including mirrors :)

* Verification:
(If it's a existing project, please provide a link to a page on project site (or othe possibly method) to verify your identity and proof that you or the contact person can represent the (sub-)project/team.)
https://wiki.almalinux.org/sigs/Infrastructure.html#sig-members

* Resource you need:
(Please describe and list down "How many, which kind (VM, web hosting, git hosting, mirror service, etc), usage (will it be what kind of function/role) and spec.")
(Please describe both the Minimal and Desired spec.)
(For slave mirror service, please also give us the source url, mirror frequecy, and other neccessary info.)
Seeking an update mirror.  Setup instructions are at https://wiki.almalinux.org/Mirrors.html

* Any additional info.

* Ability to promote OSSPlanet
As this is a free service for Open Source/Culture/Music without asking almost nothing in return,
We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.
And if it's ok for you, please let us know!

You'll be listed as a mirror provider at https://mirrors.almalinux.org :)

**Comment by bluet** [comment]
update:
- files mirrored
- twitter followed
- mailing lists subscribed
- membership applied (waiting for approval)
- said hi on mattermost/mirror channel
- PR filed (waiting for the merge and get listed on mirrors list)

**Comment by bluet** [comment]
hi @jonathanspw, when the mirror's online and been tested, would you mind giving ossplanet a review/testimonial via PR? Something like this https://github.com/OSSPlanet/OSSPlanet.github.io/pull/19/files .
Thanks!

**Comment by bluet** [comment]
hi @jonathanspw, as the mirror's up and running, would you mind giving ossplanet a review/testimonial via PR? Something like this https://github.com/OSSPlanet/OSSPlanet.github.io/pull/19/files .
Thanks!

**Comment by bluet** [comment]
closing this as no response from @jonathanspw
