### ISSUE TITLE
[OSSPlanet] GIMP Project Application for Mirror Plan

### ISSUE THREAD

**Issue by sahilister** [OSSPlanet/OSSPlanet#27]
(Please don't delete existing form title and description, just append your info/data under each section.)

* Applicant:
(Org/Project name <http://url.of.the/project/>) 
GIMP <https://www.gimp.org/>

* Project Info:

(Brief intro) 
The Free & Open Source Image Editor. GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows and more operating systems. It is [free software](https://www.gnu.org/philosophy/free-sw.html), you can change its [source code](https://git.gnome.org/browse/gimp) and [distribute](https://www.gnu.org/licenses/quick-guide-gplv3.en.html) your changes.

(Project fullname and mission)
 GNU Image Manipulation Program (GIMP) and to make a Free and Open Source Image Editor
 
(The relationship to Open Source/Culture/Music (and contribution it's it's a existing project).)
...

* Contact:
(Format: name <email>, <telegram>, <github>, <hangout>, <twitter>, etc)
(Better to have at least 1 Instant Messanger. Telegram prefered, as we have official support group here https://telegram.me/ossplanet .)
(can be more than one person)
[GIMP's infrastructure tracker](https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/new) and tagging @Jehan (GIMP co-maintainer) there.

* Who I am:
(Brief intro about who you are)
(what role in what project/team, responsible for what).
I'm Sahil (aka sahilister) a volunteer helping GIMP (and bunch of other Free Software projects) with mirrors in [India](https://mirrors.in.sahilister.net/gimp/) and [Germany](https://mirrors.de.sahilister.net/gimp/) region. See GIMP's [Mirrorbit Page](https://download.gimp.org/pub/gimp/v2.10/windows/gimp-2.10.36-setup.exe?mirrorstats).

* Verification:
(If it's a existing project, please provide a link to a page on project site (or othe possibly method) to verify your identity and proof that you or the contact person can represent the (sub-)project/team.)
See https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1592#note_2161033

* Resource you need:
(Please describe and list down "How many, which kind (VM, web hosting, git hosting, mirror service, etc), usage (will it be what kind of function/role) and spec.")
(Please describe both the Minimal and Desired spec.)
(For slave mirror service, please also give us the source url, mirror frequecy, and other neccessary info.)
A download mirror. The complete policy is given at https://www.gimp.org/news/2021/10/06/official-mirror-policy/#how-to-be-an-official-mirror . TLDR rsync credentials would be shared via secure comms (encrypted email) after creating issue on [New Mirror issue](https://gitlab.gnome.org/Infrastructure/Infrastructure/issues/new?issuable_template=new-mirror). Right now storage requirement is ~51GB.

* Any additional info.
nil.

* Ability to promote OSSPlanet
As this is a free service for Open Source/Culture/Music without asking almost nothing in return,
We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.
And if it's ok for you, please let us know!
Official mirrors are added to https://www.gimp.org/donating/sponsors.html page

Let me know if you need any other information.

**Comment by bluet** [comment]
@sahilister  ticket created https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1612

**Comment by bluet** [comment]
- https://mirror.ossplanet.net/gimp/
- rsync://mirror.ossplanet.net/gimp/
