### ISSUE TITLE
[OSSPlanet] FastStatic/Faststatic Application for VPS Plan

### ISSUE THREAD

**Issue by wtongze** [OSSPlanet/OSSPlanet#7]
(Please don't delete existing form title and description, just append your info/data under each section.)

* Applicant:
(Org/Project name <http://url.of.the/project/>)
FastStatic/FastStatic <https://github.com/faststatic/faststatic>

* Project Info:
(Brief intro)
FastStatic is a Python toolkit to help you build your own CDN of NPM packages with API support.
The official website of FastStatic(https://faststatic.com) also provides a fast, global, dual stack enabled CDN for everything on NPM.

(Project fullname and mission)
FastStatic
We help developers to publish their own packages and provide global CDN resources.
Promote utilization of IPv6.
Decrease the webpage loading time.

(The relationship to Open Source/Culture/Music (and contribution it's it's a existing project).)
FastStatic is an open source project. All the programs is on the github under MIT license.

* Contact:
(Format: name <email>, <telegram>, <github>, <hangout>, <twitter>, etc)
Tongze Wang <me@wtongze.com>, <https://t.me/wtongze>, <https://github.com/wtongze>
(Better to have at least 1 Instant Messanger. Telegram prefered.)
(can be more than one person)

* Who I am:
(Brief intro about who you are)
I am a 11th grade high school student in Beijing, China. I learned programming since I was 8. I designed an ESP8266 development board when I was in the junior high school. I have learned AP computer science in the high school and I can programming in many languages. (Python3, Java, Processing, Bash and etc.) I am passion in computer science. I currently have many VPS around the world and built a private CDN for this project in China.

(what role in what project/team, responsible for what).
I came up this project firstly and shared it with my computer science teacher. I am responsible for maintain the code and the private CDN system while others are responsible for fixing bugs.

* Verification:
(If it's a existing project, please provide a link to a page on project site (or othe possibly method) to verify your identity and proof that you or the contact person can represent the (sub-)project/team.)
Go to https://github.com/faststatic and check 'People'.
I uploaded all the code for this project.

* Resource you need:
(Please describe and list down "How many, which kind (VM, web hosting, git hosting, mirror service, etc), usage (will it be what kind of function/role) and spec.")
We need 2 VPS.
1st VPS:
- Storage for the packages
- node of the private FastStatic CDN
- API server

2nd VPS:
- Database for FastStatic and DNS
- DNS load balance server

(Please describe both the Minimal and Desired spec.)
(For slave mirror service, please also give us the source url, mirror frequecy, and other neccessary info.)
Requirement for the first VPS:
1 CPU core
At least 512mb RAM (it's better to have DDR4)
~50GB SATA3 HDD or SSD
IPv6 support

Requirement for the second VPS:
1 CPU core
At least 1gb RAM (it's better to have DDR4)
At least 10GB SATA3 HDD or SSD
IPv6 support

* Any additional info.
It's better to provide 2 VPS. It's also acceptable to provide only 1 VPS as we can chat about it.
We are still working on writing the instruction pages. Currently only English readme is available.

* Ability to promote OSSPlanet
As this is a free service for Open Source/Culture/Music without asking almost nothing in return,
We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.
And if it's ok for you, please let us know!

We will introduce your service on our website, Github readme, and cooperated media in mainland China if you can provides me the resources I needed. Thanks.

**Comment by BlueT** [comment]
Ah, this has been solved but forgot to close.

All VPS are delivered.

@wtongze could you confirm here? :)

**Comment by wtongze** [comment]
Of course😏.
