### ISSUE TITLE
[OSSPlanet] [Gitea] Git Self Hosting for Container Plan

### ISSUE THREAD

**Issue by appleboy** [OSSPlanet/OSSPlanet#8]
## Applicant
_(Org/Project name <http://url.of.the/project/>)_

Gitea: https://github.com/go-gitea

## Project Info
_(Brief intro)_  
_(Project fullname and mission)_  
_(The relationship to Open Source/Culture/Music (and contribution it's it's a existing project).)_  

The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service. Using Go, this can be done with an independent binary distribution across **all platforms** which Go supports, including Linux, macOS, and Windows on x86, amd64, ARM and PowerPC architectures. Want to try it before doing anything else? Do it [with the online demo](https://try.gitea.io/)! This project has been [forked](https://blog.gitea.io/2016/12/welcome-to-gitea/) from [Gogs](https://gogs.io).

## Contact
_(Format: name < email >, < telegram >, < github >, < hangout >, < twitter >, etc)_  
_(Better to have at least 1 Instant Messanger. Telegram prefered.)_  
_(can be more than one person)_

* Bo-Yi Wu (appleboy)
  - telegram: appleboy
  - github: https://github.com/appleboy
  - hangout: appleboy.tw@gmail.com
  - twitter: https://twitter.com/appleboy

## Who am I
_(Brief intro about who you are)_  
_(what role in what project/team, responsible for what)._

現任聯發科技後端架構工程師，喜歡嘗試任何 DevOps 工具來改善團隊合作模式，省下更多時間來嘗試及學習新技術。長期貢獻於 Open Source 專案，熱愛開發程式，目前專注於 Go 語言發展。曾任 PHPConf, JSDC, COSCUP 研討會講師，維護數個 Go 語言開源專案。詳細資料可以參考底下連結：

* Blog: https://blog.wu-boy.com
* Github: https://github.com/appleboy
* SlideShare: https://www.slideshare.net/appleboy

### 研討會經歷

* iThome Gopher Day 研討會講師 (2017)
* iThome Cloud Sumit 研討會講師 (2017)
* iThome ChatBot 研討會講師 (2017)
* iThome DevOps 研討會講師 (2016)
* PHPConf 研討會講師 (2012, 2013)
* COSCUP 研討會講師 (2016, 2014)
* JSDC 研討會講師 (2013)
* OSDC 研討會講師 (2014)

## Verification
_(If it's a existing project, please provide a link to a page on project site (or othe possibly method) to verify your identity and proof that you or the contact person can represent the (sub-)project/team.)_

All application has been stopped by DigitalOcean.

https://github.com/orgs/go-gitea/people

## Resource
_(Please describe and list down "How many, which kind (VM, web hosting, git hosting, mirror service, etc), usage (will it be what kind of function/role) and spec.")_  
_(Please describe both the Minimal and Desired spec.)_  
_(For slave mirror service, please also give us the source url, mirror frequecy, and other neccessary info.)_

We need two application VPS container.

One: (用途 CI/CD 自動化測試及部署，這邊需要較大的 Memory，以及架設 GiteaBot 用來自動審核 PR)

網站: https://drone.gitea.io

```
CPU: 4 core
OS: Ubuntu 16.04
Disk: 40G SSD?
Ram: 8G
```

other: (放官網及測試 Demo Site) 我們需要 Host 最新版 Gitea 及官網還有文件

官網: https://gitea.io
文件: https://docs.gitea.io
測試網站: https://try.gitea.io
下載 Binary 網站: https://dl.gitea.io
程式碼放置: https://code.gitea.io

```
CPU: 4 core
OS: Ubuntu 16.04
Disk: 30G SSD?
Ram: 4G
```

## Ability to promote OSSPlanet
_(As this is a free service for Open Source/Culture/Music without asking almost nothing in return,)_  
_(We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.)_  
_(And if it's ok for you, please let us know!)_

我們會在 Blog 公告一篇 OSSPlanet 贊助文，以及在官網底下放上 OSSPlanet 網站連結。

----

Update:
2017/07/24 @BlueT  
update "Project Name" to "Applicant"  
added "additional info" and "Ability to promote OSSPlanet" section

**Comment by BlueT** [comment]
Verification:
https://github.com/orgs/go-gitea/people

**Comment by BlueT** [comment]
@appleboy thanks for your application, will create your VM once info are filled. :smile:

**Comment by appleboy** [comment]
@BlueT Thanks.

**Comment by appleboy** [comment]
@BlueT UPdated.

**Comment by BlueT** [comment]
@appleboy VMs are ready
VM1
163.22.17.67
2001:e10:6840:17::67

VM2
163.22.17.68
2001:e10:6840:17::68

you already have your login info. :-)
please confirm and reply, thanks!

**Comment by appleboy** [comment]
@BlueT All servers are working now. Thanks.
